name: deploy-container

on:
  push:
    branches:
      - main
    paths:
      - 'packages/container/**' # this will run only if something in this paths changes

defaults:
  run:
    working-directory: packages/container # change directory to specific directory

jobs:
  build:
    runs-on: ubuntu-latest # operating system we choose our application to run on

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - uses: shinyinc/action-aws-cli@v1.2
      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ''
